source "https://supermarket.getchef.com"

cookbook 'apt'
cookbook 'docker',  github: "bflad/chef-docker"
cookbook "mesos", github: "everpeace/cookbook-mesos"
cookbook "marathon", github: "mdsol/marathon_cookbook"
